import {expect, test} from './fixtures';

test('profiles add, rename, save on switch, and delete without losing the route', async ({page}) => {
  await page.goto('/#/settings?from=connections');
  await page.getByRole('button', {name: 'Add profile', exact: true}).click();
  let dialog = page.getByRole('dialog', {name: 'Add profile'});
  await dialog.getByRole('textbox', {name: 'Profile name'}).fill('Home');
  await Promise.all([page.waitForEvent('load'), dialog.getByRole('button', {name: 'Save', exact: true}).click()]);
  await expect(page.locator('[name=api]')).toHaveValue('mock');
  await page.locator('[name=token]').fill('home-secret');
  await page.getByRole('button', {name: 'Add profile', exact: true}).click();
  dialog = page.getByRole('dialog', {name: 'Add profile'});
  await dialog.getByRole('textbox', {name: 'Profile name'}).fill('Office');
  await Promise.all([page.waitForEvent('load'), dialog.getByRole('button', {name: 'Save', exact: true}).click()]);
  await expect(page).toHaveURL(/#\/settings\?from=connections$/);
  await expect(page.locator('[name=token]')).toHaveValue('');
  await page.locator('[name=token]').fill('office-secret');
  await page.getByRole('button', {name: 'Backend profile'}).click();
  await Promise.all([page.waitForEvent('load'), page.getByRole('option', {name: 'Home', exact: true}).click()]);
  await expect(page).toHaveURL(/#\/settings\?from=connections$/);
  await expect(page.locator('[name=token]')).toHaveValue('home-secret');
  await page.getByRole('button', {name: 'Rename profile', exact: true}).click();
  dialog = page.getByRole('dialog', {name: 'Rename profile'});
  await dialog.getByRole('textbox', {name: 'Profile name'}).fill('Home router');
  await Promise.all([page.waitForEvent('load'), dialog.getByRole('button', {name: 'Save', exact: true}).click()]);
  await page.getByRole('button', {name: 'Delete profile', exact: true}).click();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('alertdialog')).toBeHidden();
  await page.getByRole('button', {name: 'Delete profile', exact: true}).click();
  await Promise.all([page.waitForEvent('load'), page.getByRole('alertdialog').getByRole('button', {name: 'Delete profile'}).click()]);
  await expect(page.locator('[name=token]')).toHaveValue('office-secret');
  await page.getByRole('button', {name: 'Delete profile', exact: true}).click();
  await Promise.all([page.waitForEvent('load'), page.getByRole('alertdialog').getByRole('button', {name: 'Delete profile'}).click()]);
  await page.goto('/');
  await expect(page).toHaveURL(/#\/settings$/);
  await expect(page.locator('[name=api]')).toHaveValue('');
});
