// UI strings for the shell and the activity page. Pages added later follow the same table; mock data stays as the engine reports it.
import {createContext, useContext} from 'react';

export type Lang = 'zh-TW' | 'zh-CN' | 'en';
export const LANGS: Array<[Lang, string]> = [['zh-TW', '繁體中文'], ['zh-CN', '简体中文'], ['en', 'English']];
export const S2_LOCALE: Record<Lang, string> = {'zh-TW': 'zh-TW', 'zh-CN': 'zh-CN', en: 'en-US'};

const zhTW = {
  'act.loadFailed': '無法載入活動資料。', 'lifecycle.starting': '啟動中', 'lifecycle.running': '運行中', 'lifecycle.reloading': '重載中', 'lifecycle.suspended': '已暫停', 'lifecycle.draining': '排空中', 'lifecycle.degraded': '降級', 'lifecycle.failed': '失敗', 'act.noHistory': '原生 API 不提供歷史資料', 'act.unknown': '未知',
  'nav.activity': '活動', 'nav.overview': '概覽', 'nav.connections': '連線', 'nav.clients': '客戶端', 'nav.policies': '策略', 'nav.rules': '規則', 'nav.dns': 'DNS', 'nav.resources': '資源', 'nav.config': '配置', 'nav.validate': '校驗', 'nav.events': '事件',
  'grp.status': '狀態', 'grp.network': '網路', 'grp.proxy': '代理', 'grp.system': '系統',
  'search': '搜尋連線、節點、規則', 'refresh': '重新讀取', 'refreshed': '已重新讀取，runtime r40', 'theme': '主題', 'theme.system': '跟隨系統', 'theme.light': '亮', 'theme.dark': '暗', 'palette': '配色', 'palette.glass': '毛玻璃', 'wordmark': '字標', 'wordmark.gradient': '漸層', 'wordmark.plain': '純色', 'close': '關閉', 'toast.showAll': '顯示全部', 'toast.collapse': '收合', 'toast.clearAll': '全部清除', 'clear': '清除', 'lang': '語言', 'page': '頁面', 'settings': '設定', 'github': 'GitHub 倉庫', 'search.all': '全部', 'search.nodes': '節點', 'search.none': '沒有符合的項目',
  'check.ebpf': 'eBPF datapath', 'check.route': '路由發布', 'check.tproxy': '透明監聽', 'check.nfqueue': 'NFQUEUE', 'check.dns': '獨立 DNS', 'check.api': 'Clash API', 'check.ui': '內嵌 UI',
  'act.sep': '、', 'act.sep2': '，', 'act.notReady': '未就緒', 'act.allOk': '全部檢查通過', 'act.openOverview': '打開概覽',
  'act.version': '版本', 'act.config': '配置', 'act.mode': '出站模式', 'act.global': 'Global 目標', 'act.datapath': 'datapath', 'act.iface': '介面',
  'mode.rule': '規則', 'mode.global': '全域', 'mode.direct': '直連',
  'act.probe': '探測', 'act.retest': '重測', 'act.diagnose': '診斷', 'act.probeDone': '探測完成', 'act.diagQueued': '診斷 op-1184 已排程，唯讀',
  'act.tcp': 'TCP connect', 'act.http': 'HTTP', 'act.udp': 'UDP DNS',
  'act.layout': '版式', 'act.share': '佔比', 'act.name': '名稱', 'act.bytes': '流量', 'act.conns': '連線數', 'act.latency': '延遲', 'act.ago': '{n} 分鐘前', 'act.now': '現在', 'act.peak': '峰值', 'act.avg': '平均', 'act.blocked': '拒絕', 'act.total': '本次會話總計', 'act.diagnoseNet': '網路診斷',
    'act.upload': '上傳', 'act.download': '下載', 'act.sample': '採樣 1 秒',
  'act.active': '活動連線', 'act.allConns': '全部連線', 'act.kernel': '內核', 'act.userspace': 'userspace', 'act.clients': '客戶端',
  'act.traffic': '流量', 'act.window': '最近 12 分鐘', 'act.upTotal': '上傳總計', 'act.downTotal': '下載總計', 'act.connCount': '連線數', 'act.outDist': '出站分佈', 'act.probeLatency': '節點延遲', 'act.memory': '記憶體', 'act.subtitle': '網路、代理與系統狀態一覽', 'act.viewDetails': '查看詳情', 'act.viewAll': '查看全部', 'act.viewMore': '查看更多', 'act.since': '自 {t} 起', 'act.good': '良好', 'act.live': '即時', 'act.h1': '1 小時', 'act.h6': '6 小時', 'act.h24': '24 小時', 'act.outUsage': '出站用量', 'act.lastHour': '最近 1 小時', 'act.topDevices': '裝置排行', 'act.devices': '裝置', 'act.domains': '域名', 'act.node': '節點', 'act.online': '線上', 'act.changeNode': '更換節點', 'act.lastChecked': '上次檢測', 'act.ifaces': '網路介面', 'act.ifUp': '正常', 'act.src': '來源', 'act.dst': '目的', 'act.rule': '規則', 'act.out': '出站', 'act.time': '時間', 'act.nConns': '{n} 條連線', 'act.notReadyDesc': 'NFQUEUE 運行中，但內嵌 UI 尚未就緒，不影響代理。', 'act.running': '代理運行中', 'act.issues': '通知與問題', 'act.level': '級別', 'act.content': '內容', 'act.lvlWarn': '警告', 'act.lvlErr': '錯誤', 'act.lvlInfo': '通知', 'ev.e1': 'reload 完成，r40，45 個節點，8 條規則', 'ev.e2': 'sub-b 刷新失敗，HTTP 503，沿用 r33', 'ev.e3': 'proxy，5 個成員測完，jp-01 逾時', 'ev.e4': 'NFQUEUE 未就緒，nfnetlink_queue 未載入', 'ev.e5': 'diagnose op-1183 完成，7 項檢查，2 項失敗', 'ev.e6': '啟動，honk 0.9.3，eBPF datapath 已掛 wan0、lan0', 'act.recentEvents': '最近事件', 'act.ruleHits': '規則命中', 'act.hits': '{n} 次', 'act.dnsCache': 'DNS 快取', 'act.entries': '條目', 'act.posCache': '正快取', 'act.negCache': '負快取', 'act.upstreams': '上游', 'act.noIssues': '沒有待處理的問題', 'act.timeout': '逾時', 'act.filterNodes': '篩選節點', 'act.loading': '載入中…', 'act.nTimeouts': '{n} 個節點逾時：{list}', 'act.needRestart': '需重啟', 'act.view': '查看', 'act.coreOk': '核心服務正常', 'act.reloadConfig': '重新載入配置', 'act.flushDns': '清除 DNS 快取', 'act.events': '事件', 'act.d7': '7 天', 'act.vsPrev': '較前一段', 'act.bySrc': '來源 IP', 'act.byHost': '域名', 'act.byOut': '出站', 'act.trafficNote': '只計可見流，本次瀏覽器會話內的採樣，不持久。'
};
type Key = keyof typeof zhTW;
const zhCN: Record<Key, string> = {
  'act.loadFailed': '无法加载活动数据。', 'lifecycle.starting': '启动中', 'lifecycle.running': '运行中', 'lifecycle.reloading': '重载中', 'lifecycle.suspended': '已暂停', 'lifecycle.draining': '排空中', 'lifecycle.degraded': '降级', 'lifecycle.failed': '失败', 'act.noHistory': '原生 API 不提供历史数据', 'act.unknown': '未知',
  'nav.activity': '活动', 'nav.overview': '概览', 'nav.connections': '连接', 'nav.clients': '客户端', 'nav.policies': '策略', 'nav.rules': '规则', 'nav.dns': 'DNS', 'nav.resources': '资源', 'nav.config': '配置', 'nav.validate': '校驗', 'nav.events': '事件',
  'grp.status': '状态', 'grp.network': '网络', 'grp.proxy': '代理', 'grp.system': '系统',
  'search': '搜索连接、节点、规则', 'refresh': '重新读取', 'refreshed': '已重新读取，runtime r40', 'theme': '主题', 'theme.system': '跟随系统', 'theme.light': '亮', 'theme.dark': '暗', 'palette': '配色', 'palette.glass': '毛玻璃', 'wordmark': '字標', 'wordmark.gradient': '漸層', 'wordmark.plain': '純色', 'close': '关闭', 'toast.showAll': '显示全部', 'toast.collapse': '折叠', 'toast.clearAll': '全部清除', 'clear': '清除', 'lang': '语言', 'page': '页面', 'settings': '设置', 'github': 'GitHub 仓库', 'search.all': '全部', 'search.nodes': '节点', 'search.none': '没有符合的项目',
  'check.ebpf': 'eBPF datapath', 'check.route': '路由发布', 'check.tproxy': '透明监听', 'check.nfqueue': 'NFQUEUE', 'check.dns': '独立 DNS', 'check.api': 'Clash API', 'check.ui': '内嵌 UI',
  'act.sep': '、', 'act.sep2': '，', 'act.notReady': '未就绪', 'act.allOk': '全部检查通过', 'act.openOverview': '打开概览',
  'act.version': '版本', 'act.config': '配置', 'act.mode': '出站模式', 'act.global': 'Global 目标', 'act.datapath': 'datapath', 'act.iface': '接口',
  'mode.rule': '规则', 'mode.global': '全局', 'mode.direct': '直连',
  'act.probe': '探测', 'act.retest': '重测', 'act.diagnose': '诊断', 'act.probeDone': '探测完成', 'act.diagQueued': '诊断 op-1184 已排队，只读',
  'act.tcp': 'TCP connect', 'act.http': 'HTTP', 'act.udp': 'UDP DNS',
  'act.layout': '版式', 'act.share': '占比', 'act.name': '名称', 'act.bytes': '流量', 'act.conns': '连接数', 'act.latency': '延迟', 'act.ago': '{n} 分钟前', 'act.now': '现在', 'act.peak': '峰值', 'act.avg': '平均', 'act.blocked': '拒绝', 'act.total': '本次会话总计', 'act.diagnoseNet': '网络诊断',
    'act.upload': '上传', 'act.download': '下载', 'act.sample': '采样 1 秒',
  'act.active': '活动连接', 'act.allConns': '全部连接', 'act.kernel': '内核', 'act.userspace': 'userspace', 'act.clients': '客户端',
  'act.traffic': '流量', 'act.window': '最近 12 分钟', 'act.upTotal': '上传总计', 'act.downTotal': '下载总计', 'act.connCount': '连接数', 'act.outDist': '出站分布', 'act.probeLatency': '节点延迟', 'act.memory': '内存', 'act.subtitle': '网络、代理与系统状态一览', 'act.viewDetails': '查看详情', 'act.viewAll': '查看全部', 'act.viewMore': '查看更多', 'act.since': '自 {t} 起', 'act.good': '良好', 'act.live': '实时', 'act.h1': '1 小时', 'act.h6': '6 小时', 'act.h24': '24 小时', 'act.outUsage': '出站用量', 'act.lastHour': '最近 1 小时', 'act.topDevices': '设备排行', 'act.devices': '设备', 'act.domains': '域名', 'act.node': '节点', 'act.online': '在线', 'act.changeNode': '更换节点', 'act.lastChecked': '上次检测', 'act.ifaces': '网络接口', 'act.ifUp': '正常', 'act.src': '来源', 'act.dst': '目的', 'act.rule': '规则', 'act.out': '出站', 'act.time': '时间', 'act.nConns': '{n} 条连接', 'act.notReadyDesc': 'NFQUEUE 运行中，但内嵌 UI 尚未就绪，不影响代理。', 'act.running': '代理运行中', 'act.issues': '通知与问题', 'act.level': '级别', 'act.content': '内容', 'act.lvlWarn': '警告', 'act.lvlErr': '错误', 'act.lvlInfo': '通知', 'ev.e1': 'reload 完成，r40，45 个节点，8 条规则', 'ev.e2': 'sub-b 刷新失败，HTTP 503，沿用 r33', 'ev.e3': 'proxy，5 个成员测完，jp-01 超时', 'ev.e4': 'NFQUEUE 未就绪，nfnetlink_queue 未加载', 'ev.e5': 'diagnose op-1183 完成，7 项检查，2 项失败', 'ev.e6': '启动，honk 0.9.3，eBPF datapath 已挂 wan0、lan0', 'act.recentEvents': '最近事件', 'act.ruleHits': '规则命中', 'act.hits': '{n} 次', 'act.dnsCache': 'DNS 缓存', 'act.entries': '条目', 'act.posCache': '正缓存', 'act.negCache': '负缓存', 'act.upstreams': '上游', 'act.noIssues': '没有待处理的问题', 'act.timeout': '超时', 'act.filterNodes': '筛选节点', 'act.loading': '加载中…', 'act.nTimeouts': '{n} 个节点超时：{list}', 'act.needRestart': '需重启', 'act.view': '查看', 'act.coreOk': '核心服务正常', 'act.reloadConfig': '重新加载配置', 'act.flushDns': '清除 DNS 缓存', 'act.events': '事件', 'act.d7': '7 天', 'act.vsPrev': '较前一段', 'act.bySrc': '来源 IP', 'act.byHost': '域名', 'act.byOut': '出站', 'act.trafficNote': '只计可见流，本次浏览器会话内的采样，不持久。'
};
const en: Record<Key, string> = {
  'act.loadFailed': 'Could not load activity data.', 'lifecycle.starting': 'Starting', 'lifecycle.running': 'Running', 'lifecycle.reloading': 'Reloading', 'lifecycle.suspended': 'Suspended', 'lifecycle.draining': 'Draining', 'lifecycle.degraded': 'Degraded', 'lifecycle.failed': 'Failed', 'act.noHistory': 'The native API does not provide history', 'act.unknown': 'Unknown',
  'nav.activity': 'Activity', 'nav.overview': 'Overview', 'nav.connections': 'Connections', 'nav.clients': 'Clients', 'nav.policies': 'Policies', 'nav.rules': 'Rules', 'nav.dns': 'DNS', 'nav.resources': 'Resources', 'nav.config': 'Config', 'nav.validate': 'Validate', 'nav.events': 'Events',
  'grp.status': 'Status', 'grp.network': 'Network', 'grp.proxy': 'Proxy', 'grp.system': 'System',
  'search': 'Search connections, nodes, rules', 'refresh': 'Reload data', 'refreshed': 'Reloaded, runtime r40', 'theme': 'Theme', 'theme.system': 'System', 'theme.light': 'Light', 'theme.dark': 'Dark', 'palette': 'Palette', 'palette.glass': 'Frosted glass', 'wordmark': 'Wordmark', 'wordmark.gradient': 'Gradient', 'wordmark.plain': 'Plain', 'close': 'Close', 'toast.showAll': 'Show all', 'toast.collapse': 'Collapse', 'toast.clearAll': 'Clear all', 'clear': 'Clear', 'lang': 'Language', 'page': 'Page', 'settings': 'Settings', 'github': 'GitHub repository', 'search.all': 'All', 'search.nodes': 'Nodes', 'search.none': 'No matches',
  'check.ebpf': 'eBPF datapath', 'check.route': 'Route publishing', 'check.tproxy': 'Transparent listener', 'check.nfqueue': 'NFQUEUE', 'check.dns': 'Standalone DNS', 'check.api': 'Clash API', 'check.ui': 'Embedded UI',
  'act.sep': ', ', 'act.sep2': ', ', 'act.notReady': 'not ready', 'act.allOk': 'All checks passed', 'act.openOverview': 'Open overview',
  'act.version': 'Version', 'act.config': 'Config', 'act.mode': 'Mode', 'act.global': 'Global target', 'act.datapath': 'datapath', 'act.iface': 'Interfaces',
  'mode.rule': 'Rule', 'mode.global': 'Global', 'mode.direct': 'Direct',
  'act.probe': 'Probe', 'act.retest': 'Retest', 'act.diagnose': 'Diagnose', 'act.probeDone': 'probe finished', 'act.diagQueued': 'Diagnose op-1184 queued, read-only',
  'act.tcp': 'TCP connect', 'act.http': 'HTTP', 'act.udp': 'UDP DNS',
  'act.layout': 'Layout', 'act.share': 'Share', 'act.name': 'Name', 'act.bytes': 'Bytes', 'act.conns': 'Connections', 'act.latency': 'Latency', 'act.ago': '{n} min ago', 'act.now': 'now', 'act.peak': 'Peak', 'act.avg': 'Average', 'act.blocked': 'Blocked', 'act.total': 'Session total', 'act.diagnoseNet': 'Diagnosis',
    'act.upload': 'Upload', 'act.download': 'Download', 'act.sample': '1 s sample',
  'act.active': 'Active connections', 'act.allConns': 'All connections', 'act.kernel': 'Kernel', 'act.userspace': 'userspace', 'act.clients': 'Clients',
  'act.traffic': 'Traffic', 'act.window': 'last 12 min', 'act.upTotal': 'Uploaded', 'act.downTotal': 'Downloaded', 'act.connCount': 'Connections', 'act.outDist': 'By outbound', 'act.probeLatency': 'Node latency', 'act.memory': 'Memory', 'act.subtitle': 'A quick view of network, proxy and system status', 'act.viewDetails': 'Details', 'act.viewAll': 'View all', 'act.viewMore': 'View more', 'act.since': 'Since {t}', 'act.good': 'Good', 'act.live': 'Live', 'act.h1': '1H', 'act.h6': '6H', 'act.h24': '24H', 'act.outUsage': 'Outbound usage', 'act.lastHour': 'last hour', 'act.topDevices': 'Top devices', 'act.devices': 'Devices', 'act.domains': 'Domains', 'act.node': 'Node', 'act.online': 'Online', 'act.changeNode': 'Change node', 'act.lastChecked': 'Last checked', 'act.ifaces': 'Network interfaces', 'act.ifUp': 'Up', 'act.src': 'Source', 'act.dst': 'Destination', 'act.rule': 'Rule', 'act.out': 'Outbound', 'act.time': 'Since', 'act.nConns': '{n} connections', 'act.notReadyDesc': 'NFQUEUE is running but the embedded UI is not ready. Proxying is unaffected.', 'act.running': 'Running', 'act.issues': 'Notifications', 'act.level': 'Level', 'act.content': 'Details', 'act.lvlWarn': 'Warning', 'act.lvlErr': 'Error', 'act.lvlInfo': 'Notice', 'ev.e1': 'Reload done, r40, 45 nodes, 8 rules', 'ev.e2': 'sub-b refresh failed, HTTP 503, keeping r33', 'ev.e3': 'proxy, 5 members probed, jp-01 timed out', 'ev.e4': 'NFQUEUE not ready, nfnetlink_queue not loaded', 'ev.e5': 'diagnose op-1183 done, 7 checks, 2 failed', 'ev.e6': 'Started, honk 0.9.3, eBPF datapath attached to wan0, lan0', 'act.recentEvents': 'Recent events', 'act.ruleHits': 'Rule hits', 'act.hits': '{n}', 'act.dnsCache': 'DNS cache', 'act.entries': 'Entries', 'act.posCache': 'Positive', 'act.negCache': 'Negative', 'act.upstreams': 'Upstreams', 'act.noIssues': 'Nothing needs attention', 'act.timeout': 'timed out', 'act.filterNodes': 'Filter nodes', 'act.loading': 'Loading…', 'act.nTimeouts': '{n} nodes timed out: {list}', 'act.needRestart': 'restart needed', 'act.view': 'View', 'act.coreOk': 'Core services OK', 'act.reloadConfig': 'Reload config', 'act.flushDns': 'Flush DNS cache', 'act.events': 'Events', 'act.d7': '7D', 'act.vsPrev': 'vs previous', 'act.bySrc': 'Source IP', 'act.byHost': 'Domain', 'act.byOut': 'Outbound', 'act.trafficNote': 'Visible flows only, sampled during this browser session, not persisted.'
};
const TABLES: Record<Lang, Record<Key, string>> = {'zh-TW': zhTW, 'zh-CN': zhCN, en};

export const LangContext = createContext<Lang>('zh-TW');
export function useT() { const lang = useContext(LangContext); return (k: Key) => TABLES[lang][k]; }
export function readLang(): Lang { try { const v = localStorage.getItem('doona-lang'); return v === 'zh-CN' || v === 'en' ? v : 'zh-TW'; } catch { return 'zh-TW'; } }
