// Common proxy regions in picker order, with aliases for name-based detection.
type RegionNames = {short: Partial<Record<string, string>>; official?: string[]};
export const regions: Array<[string, string[], RegionNames?]> = [
  [
    'HK',
    ['hk', 'hkg', 'hongkong', 'hong kong', '香港', '港'],
    {short: {en: 'Hong Kong', 'zh-TW': '香港', 'zh-CN': '香港'}, official: ['Hong Kong SAR China', '中國香港特別行政區', '中国香港特别行政区']}
  ],
  ['TW', ['tw', 'tpe', 'taiwan', 'taipei', '台灣', '台湾', '臺灣', '台北'], {short: {en: 'Taiwan', 'zh-TW': '台灣', 'zh-CN': '台湾'}}],
  ['JP', ['jp', 'jpn', 'japan', 'tokyo', 'osaka', 'nrt', 'hnd', 'kix', '日本', '東京', '东京', '大阪']],
  ['SG', ['sg', 'sgp', 'singapore', 'sin', '新加坡', '獅城', '狮城']],
  [
    'US',
    [
      'us',
      'usa',
      'united states',
      'america',
      'lax',
      'sjc',
      'sea',
      'nyc',
      'los angeles',
      'san jose',
      'seattle',
      '美國',
      '美国',
      '洛杉磯',
      '洛杉矶',
      '聖何塞',
      '圣何塞',
      '西雅圖',
      '西雅图'
    ]
  ],
  ['KR', ['kr', 'kor', 'korea', 'seoul', 'icn', 'south korea', '南韩', '南韓', '韓國', '韩国', '首爾', '首尔'], {short: {'zh-TW': '韓國'}}],
  ['CA', ['can', 'canada', 'toronto', 'yyz', '加拿大']],
  ['GB', ['gb', 'uk', 'united kingdom', 'britain', 'london', 'lhr', '英國', '英国', '倫敦', '伦敦']],
  ['DE', ['de', 'deu', 'germany', 'frankfurt', 'fra', '德國', '德国', '法蘭克福', '法兰克福']],
  ['FR', ['fr', 'france', 'paris', 'cdg', '法國', '法国', '巴黎']],
  ['NL', ['nl', 'nld', 'netherlands', 'amsterdam', 'ams', '荷蘭', '荷兰', '阿姆斯特丹']],
  ['RU', ['ru', 'rus', 'russia', 'moscow', '俄羅斯', '俄罗斯', '莫斯科']],
  ['AU', ['au', 'aus', 'australia', 'sydney', 'syd', '澳洲', '澳大利亞', '澳大利亚', '悉尼']],
  ['IN', ['in', 'ind', 'india', 'mumbai', 'bom', '印度', '孟買', '孟买']],
  ['TR', ['tr', 'tur', 'turkey', 'türkiye', 'istanbul', '土耳其']],
  ['BR', ['br', 'bra', 'brazil', 'sao paulo', 'gru', '巴西']],
  ['AR', ['ar', 'arg', 'argentina', '阿根廷']],
  ['MY', ['my', 'mys', 'malaysia', 'kul', '馬來西亞', '马来西亚']],
  ['TH', ['th', 'tha', 'thailand', 'bangkok', 'bkk', '泰國', '泰国']],
  ['VN', ['vn', 'vnm', 'vietnam', '越南']],
  ['PH', ['ph', 'phl', 'philippines', 'manila', '菲律賓', '菲律宾']],
  ['ID', ['id', 'idn', 'indonesia', 'jakarta', '印度尼西亚', '印度尼西亞', '印尼']],
  ['AE', ['ae', 'are', 'uae', 'united arab emirates', '阿联酋', '阿聯酋', 'dubai', 'dxb', '阿聯', '阿联', '杜拜', '迪拜']],
  ['CH', ['ch', 'che', 'switzerland', 'zurich', '瑞士']],
  ['SE', ['se', 'swe', 'sweden', 'stockholm', '瑞典']],
  ['FI', ['fi', 'fin', 'finland', 'helsinki', '芬蘭', '芬兰']],
  ['IT', ['it', 'ita', 'italy', 'milan', '義大利', '意大利']],
  ['ES', ['es', 'esp', 'spain', 'madrid', '西班牙']],
  ['PL', ['pl', 'pol', 'poland', 'warsaw', '波蘭', '波兰']],
  [
    'MO',
    ['mo', 'mac', 'macau', 'macao', '澳門', '澳门'],
    {short: {en: 'Macao', 'zh-TW': '澳門', 'zh-CN': '澳门'}, official: ['Macao SAR China', '中國澳門特別行政區', '中国澳门特别行政区']}
  ],
  ['NZ', ['new zealand', '新西兰', '紐西蘭']],
  ['MX', ['mexico', '墨西哥']],
  ['NO', ['norway', '挪威']],
  ['DK', ['denmark', '丹麦', '丹麥']],
  ['IE', ['ireland', '爱尔兰', '愛爾蘭']],
  ['ZA', ['south africa', '南非']],
  ['IL', ['israel', '以色列']],
  ['UA', ['ukraine', '乌克兰', '烏克蘭']],
  ['PT', ['portugal', '葡萄牙']],
  ['CN', ['cn', 'chn', 'china', 'shanghai', 'beijing', 'shenzhen', '中國', '中国', '上海', '北京', '深圳']]
];
