#!/usr/bin/env node
// Writes src/i18n/locales/{zh-TW,zh-CN,en}.ts from every messages.ts, one module per language, so a build ships
// each language as its own chunk and the page loads only the one it shows. Authors keep editing messages.ts; the
// literals there are read with the TypeScript compiler, never evaluated.
//   node tools/gen-locales.mjs            write the modules
//   node tools/gen-locales.mjs --check    exit 1 when they are stale
import {globSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join, relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';
import prettier from 'prettier';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const langs = ['zh-TW', 'zh-CN', 'en'];
const sources = globSync(['src/shell/messages.ts', 'src/ui/messages.ts', 'src/features/*/messages.ts', 'src/features/*/*/messages.ts'], {cwd: root}).sort();

const fail = (file, node, why) => {
  const source = node.getSourceFile();
  const {line} = source.getLineAndCharacterOfPosition(node.getStart(source));
  throw new Error(`${file}:${line + 1}: ${why}`);
};
const name = (file, node) => {
  if (ts.isIdentifier(node) || ts.isStringLiteral(node)) return node.text;
  fail(file, node, 'a message key must be an identifier or a string literal');
};
const text = node => (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node) ? node.text : undefined);
const message = (file, node) => {
  const plain = text(node);
  if (plain !== undefined) return plain;
  if (ts.isObjectLiteralExpression(node)) {
    const forms = Object.fromEntries(node.properties.map(p => [name(file, p.name), ts.isPropertyAssignment(p) ? text(p.initializer) : undefined]));
    if (Object.keys(forms).sort().join() === 'one,other' && typeof forms.one === 'string' && typeof forms.other === 'string') return forms;
  }
  fail(file, node, 'a message must be a string literal or {one, other} string literals');
};

function read(file) {
  const source = ts.createSourceFile(file, readFileSync(join(root, file), 'utf8'), ts.ScriptTarget.Latest, true);
  let found;
  const visit = node => {
    if (ts.isCallExpression(node) && ts.isIdentifier(node.expression) && node.expression.text === 'defineMessages') {
      if (found) fail(file, node, 'one defineMessages call per file');
      found = node.arguments[0];
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  if (!found || !ts.isObjectLiteralExpression(found)) throw new Error(`${file}: no defineMessages({...}) call`);
  const catalogue = {};
  for (const property of found.properties) {
    if (!ts.isPropertyAssignment(property) || !ts.isObjectLiteralExpression(property.initializer)) fail(file, property, 'expected a language object');
    const lang = name(file, property.name);
    if (!langs.includes(lang)) fail(file, property, `unknown language ${lang}`);
    catalogue[lang] = {};
    for (const entry of property.initializer.properties) {
      if (!ts.isPropertyAssignment(entry)) fail(file, entry, 'expected key: message');
      catalogue[lang][name(file, entry.name)] = message(file, entry.initializer);
    }
  }
  for (const lang of langs) if (!catalogue[lang]) throw new Error(`${file}: no ${lang} messages`);
  return catalogue;
}

const merged = Object.fromEntries(langs.map(lang => [lang, {}]));
const owners = new Map();
for (const file of sources) {
  const catalogue = read(file);
  for (const key of Object.keys(catalogue['zh-TW'])) {
    if (owners.has(key)) throw new Error(`${file}: ${key} is already defined in ${owners.get(key)}`);
    owners.set(key, file);
  }
  for (const lang of langs) Object.assign(merged[lang], catalogue[lang]);
}

const header = `// Generated by tools/gen-locales.mjs from ${sources.length} messages.ts files; edit those, then run pnpm gen:locales.\n`;
const body = lang =>
  lang === 'zh-TW'
    ? `${header}import type {Message} from '../index';\n\nexport const messages = ${JSON.stringify(merged[lang])} satisfies Record<string, Message>;\nexport type Key = keyof typeof messages;\n`
    : `${header}import type {Message} from '../index';\nimport type {Key} from './zh-TW';\n\nexport const messages = ${JSON.stringify(merged[lang])} satisfies Record<Key, Message>;\n`;

const check = process.argv.includes('--check');
const options = await prettier.resolveConfig(join(root, 'src/i18n/index.ts'));
let stale = false;
mkdirSync(join(root, 'src/i18n/locales'), {recursive: true});
for (const lang of langs) {
  const path = join(root, 'src/i18n/locales', `${lang}.ts`);
  const output = await prettier.format(body(lang), {...options, filepath: path});
  let current = '';
  try {
    current = readFileSync(path, 'utf8');
  } catch {}
  if (current === output) continue;
  if (check) {
    stale = true;
    console.error(`${relative(root, path)} differs from the messages.ts sources; run pnpm gen:locales.`);
  } else writeFileSync(path, output);
}
if (stale) process.exit(1);
